language: rust
rust:
    - nightly
    - stable

install:
  - export CXX="g++-4.8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports     # recent version of cmake
    packages:
    - gcc-4.8
    - g++-4.8       # required to compile glslang
    - clang
    - cmake
    - cmake-data

script:
    # Check whitespace with git
    - git diff-tree --check $(git hash-object -t tree /dev/null) HEAD
    - cargo test -v --manifest-path glsl-to-spirv/Cargo.toml
    - cargo test -v --manifest-path vulkano-shaders/Cargo.toml
    - cargo test -v --manifest-path vulkano-shader-derive/Cargo.toml
    # We run the projects that depend on vulkano with `-j 1` or we have a
    # chance to reach travis' memory limit
    - cargo test -j 1 --manifest-path vulkano-win/Cargo.toml
    - cargo test --no-run -j 1 -v --manifest-path vulkano/Cargo.toml
    - cargo test --doc -j 1 -v --manifest-path vulkano/Cargo.toml
    - cargo build -j 1 --manifest-path examples/Cargo.toml

after_success:
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --token ${CRATESIO_TOKEN} --manifest-path vk-sys/Cargo.toml
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --token ${CRATESIO_TOKEN} --manifest-path vulkano/Cargo.toml
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --token ${CRATESIO_TOKEN} --manifest-path vulkano-win/Cargo.toml
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --token ${CRATESIO_TOKEN} --manifest-path glsl-to-spirv/Cargo.toml
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --token ${CRATESIO_TOKEN} --manifest-path vulkano-shaders/Cargo.toml
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --token ${CRATESIO_TOKEN} --manifest-path vulkano-shader-derive/Cargo.toml
